apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: about-website
  namespace: heezy
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: public
  rules:
  - host: about.trentnielsen.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: about-website
            port:
              number: 80
