apiVersion: v1
kind: Service
metadata:
  name: about-website
  namespace: heezy
spec:
  selector:
    app: about-website
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
